### ISSUE TITLE
Saving files in a standardize way to then be used in operations 

### ISSUE THREAD

**Issue by FatimaPillosu** [esowc/ecPoint-Calibrate#115] opened 2020-10-08 16:48 UTC
In operations we need a highly standardize format, otherwise the forecast production might get broken.
For this reason, we might want to include a button, called perhaps "Save Oper Files", that will save in a standard format all the files that are needed in operations, and save them in a directory ready to be passed to the operators and to be stored in our archive.

This issue is also directly linked with other two issues: #99, #96 and #107 .

**Comment by FatimaPillosu** [comment] 2020-11-18 15:13
Creation of a README.txt that contains the following information of the calibration produced:
******************************************
ecPoint-[family], [Acc]-hourly 
Version [Cal_Vers]
Date and time of creation: [date], [time]
******************************************

Meaning of words in brackets:
**family**: rainfall, temperature, wind, etc (To be inserted in a text box)
Cal_Vers: version was given to the calibration (To be inserted in a text box). Example, Cal_Vers=1.1.0-alpha (SemVer2.0 format)

**Comment by FatimaPillosu** [comment] 2020-11-18 15:29
Creation of an output button that will make appear a menu where the user can select to save:
- Breakpoints.csv: **(which value will replace -inf and inf)**
- FER.csv (or FE.csv): **(number of columns)**
- All WTs: _NOTE: the user will need to select (or create) the directory that will contain the weather types._
- Save all outputs. **(Default name of the directory will be OperCalOuts_[Cal_Vers])** _Note: in this case, all the WTs will be saved in a sub-directory called always "WTs". The user will need to select the location for the directory._ 

Each option will open a dedicated pop-window that requests the user to insert the needed information to create the files, indicated in bold.

**Comment by onyb** [comment] 2020-11-30 19:51
Fixed in [v0.15.0](https://github.com/esowc/ecPoint-Calibrate/releases/tag/v0.15.0). Feel free to reopen if the issue is still not solved, or if you have questions.

**Closed by onyb** 2020-11-30 19:51 UTC
Labels: bug, enhancement
