### ISSUE TITLE
Clicking on non-leaf nodes throws an error

### ISSUE THREAD

**Issue by AugustinVintzileos** [esowc/ecPoint-Calibrate#127] opened 2020-11-15 19:08 UTC
Hello - 
I clicked on the second level of nodes and received a 500- internal server problem message with the following traceback

![image](https://user-images.githubusercontent.com/72265581/99193962-56aa5a00-274a-11eb-8cc2-719de3ca9122.png)
![image](https://user-images.githubusercontent.com/72265581/99193982-7e012700-274a-11eb-844d-418f6472ef87.png)
![Image1](https://user-images.githubusercontent.com/72265581/99194212-0c29dd00-274c-11eb-903e-811137947384.png)

Sorry about the png but I had copy&paste issues

**Comment by onyb** [comment] 2020-11-15 20:51
@AugustinVintzileos I was able to reproduce the error but would like to understand the expected behaviour. Normally, it's supposed to collapse the subtree, and not display any error in the console. Is that correct?

**Comment by AugustinVintzileos** [comment] 2020-11-15 20:57
At the non edit mode I would expect to see a distribution of 2-meter temperature errors. Actually, I got a 500- error when I asked the K-S test to split in only one value the first node so I wonder whether this is coming from arithmetic operations resulting to NaNs ?

**Comment by onyb** [comment] 2020-11-15 22:42
> At the non edit mode I would expect to see a distribution of 2-meter temperature errors.

As fas as I remember, this feature was never supported, although the console error is not expected. Viewing the error histograms is something that's only supported in "leaf nodes", i.e., nodes without any children.

The histogram at the desired node can be obtained by either clicking on the node before it is split or by merging together all its children. Once split, clicking on the node will only collapse/un-collapse the child nodes.

Maybe @FatimaPillosu can clarify this point.

**Comment by AugustinVintzileos** [comment] 2020-11-15 23:05
Great! Out of curiosity what is this 500- error about?

**Comment by onyb** [comment] 2020-11-16 00:32
It's due to a misfired event. Clicking on that node triggered a "collapse sub-tree" event, and at the same time a call to the backend to process the histogram (with wrong inputs). Only the first event should've been fired since it's a non-leaf node.

The fix will be to correctly recognize a non-lead node and prevent the superfluous event from getting fired.

**Comment by onyb** [comment] 2020-11-22 13:18
Fixed in **v0.14.0**.

**Closed by onyb** 2020-11-22 13:18 UTC
Labels: bug
