### ISSUE TITLE
Conditional verification maps do not render fonts

### ISSUE THREAD

**Issue by AugustinVintzileos** [esowc/ecPoint-Calibrate#125] opened 2020-11-10 00:54 UTC
Hello - The observation frequency diagnostic is great but needs fonts - Augustin

**Comment by FatimaPillosu** [comment] 2020-11-10 06:38
Hi Augustin, thanks! But could you please add more detail to the current issue? What do you mean for the observation frequency diagnostix? Which fonts are needed? You could grab the screen to show us where the problem is.
Cheers,
Fatima

**Comment by EstiGascon** [comment] 2020-11-10 08:25
I think he refers to the observations frequency map, which is plotted properly, but we cannot see titles, coordinates and any text at all, only square empty boxes. I already created an issue about it in the past.

**Comment by AugustinVintzileos** [comment] 2020-11-10 13:06
Esti is right. An example can be seen here  /home/mo/mova/CV_90.pdf
By the way I think that it is easier to manipulate .png fies e.g., including graphs in powerpoint, word etc. It is definitively not a priority, but it would be nice to be able to choose additional formats.


________________________________

**Comment by onyb** [comment] 2020-11-10 17:26
I think I know what you're talking about. If you save the PDF to disk, and open it with a PDF reader, you'll be able to see everything just fine. The issue is only while displaying PDFs on the GUI - I suspect it's because the PDF renderer we use is not so powerful.

**Comment by onyb** [comment] 2020-11-22 13:18
This has been fixed in **v0.14.0**, which also includes other improvements to the rendering of conditional verification maps.

Please reopen if the issue is still not resolved.

**Closed by onyb** 2020-11-22 13:18 UTC
Labels: bug
