### ISSUE TITLE
Allow to have accumulated predictors with instantaneous predictand

### ISSUE THREAD

**Issue by EstiGascon** [esowc/ecPoint-Calibrate#113] opened 2020-10-05 08:46 UTC
Currently, it is not possible, but it would be good to have an option of accumulated predictor for an instantaneous predictand in which we can indicate the starting time and end time of the accumulation period (i.e. if our predictand is instantaneous 2m temperature, include the local solar time of the previous 6 hours as a predictor, or the precipitation in the last 3 hours before the valid time). This aspect is really important for the local solar time, as currently we are doing this computation manually out of the calibration software.

**Comment by FatimaPillosu** [comment] 2020-10-05 14:18
Hi @EstiGascon ,
is this relevant for many variables or is this valid only for the examples that you gave?
If it is only valid for a few cases, maybe it would be better to add only specific computations to stop users computing things that might make not much sense.
Cheers,
Fatima

**Comment by EstiGascon** [comment] 2020-10-05 14:40
Hi @FatimaPillosu,

Currently, we would need it only for the computation of solar-radiation, but it could be important in the future for other accumulated variables as precipitation (please, let me discuss it with Tim first). It would be enough, for now, to include as an option the computation of 24h solar radiation (in the previous 24 hours of the valid time, for example) and that's all.

**Comment by FatimaPillosu** [comment] 2020-10-05 15:06
Let's see what Tim suggests. 
It is just a matter to see whether it is valuable to invest time in doing something more flexible or not. 
But in principle, it is a good idea. 
So the problem is to think whether there could be many other accumulated parameters that could be relevant for the post-processing of not accumulated predictands.

**Comment by FatimaPillosu** [comment] 2021-03-24 14:48
Hi, 
I've been thinking about this issue and because I think this might overcomplicate the computations section (do we want to accumulate over what period? It is not specified because the predictand is instantaneous), I think is best if this is a predictor that is pre-computed separately and considered later on in the software as instantaneous. Thus, I will close this issue. but if someone has anything else to say about, please feel free to repone the issue.
Cheers,
Fatima

**Closed by FatimaPillosu** 2021-03-24 14:48 UTC
Labels: Science
