### ISSUE TITLE
More flexibility to modify the BreakpointsWT.csv file

### ISSUE THREAD

**Issue by EstiGascon** [esowc/ecPoint-Calibrate#167] opened 2021-03-26 12:02 UTC
I have tried to upload a BreakpointsWT.csv which, apparently, had exactly the same format that the ones generated by the Calibration software. However it did not load it, the software was just stacked in a "white screen" and I had to restart the software again.  
I also tried to create a really simple BreakpointsWT.csv file with only 4 weather types, using the software and saving the file. Then, I opened it as a text file, I removed the last weather type (the last line of the file), saved it and I tried to load the file again in the software, but it failed. I do not understand why it did not work, but the option of being able to modify the file by yourself (keeping the format) it would be really useful and I am not sure why this option is failing.

**Comment by ATimHewson** [comment] 2021-03-26 12:37
Esti - not sure but could this be a simple excess/deficit of carriage returns in your files? Note sure how "fussy" the software could be?

**Comment by FatimaPillosu** [comment] 2021-04-21 15:15
Hi, 
now, re-reading this issue, I don't think that it is such a bad thing the software doesn't allow to read ascii tables modified by users. The problem is by chance there is something wrong with the point data table, the software can start doing funny things and we might not realize it. I would actually prefer the software doesn't read user-modified point data tables. 
What do you think @onyb ?

Cheers,

Fatima

**Comment by FatimaPillosu** [comment] 2021-05-05 09:58
Hi, 
I will close this issue as I don't think that allowing more flexibility on uploading user-modified files is good for the software. It could bring problems, and I think that, given the small amount of time left, there are other things that are more important. 
However, I leave it to @onyb to reconsider whether to open or not this issue if he considers this can be done without major problems.
Cheers,
Fatima

**Closed by FatimaPillosu** 2021-05-05 09:58 UTC
Labels: enhancement, priority 3
